
package fr.afcepf.atod26.lebaronjerome;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceWeb", targetNamespace = "http://lebaronjerome.atod26.afcepf.fr")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IServiceWeb {


    /**
     * 
     * @param paramDeuxieme
     * @param paramPremier
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "resultatMultiplication", partName = "resultatMultiplication")
    public int multiplier(
        @WebParam(name = "paramPremier", partName = "paramPremier")
        int paramPremier,
        @WebParam(name = "paramDeuxieme", partName = "paramDeuxieme")
        int paramDeuxieme);

    /**
     * 
     * @param paramDeuxieme
     * @param paramPremier
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "resultatAddition", partName = "resultatAddition")
    public int ajouter(
        @WebParam(name = "paramPremier", partName = "paramPremier")
        int paramPremier,
        @WebParam(name = "paramDeuxieme", partName = "paramDeuxieme")
        int paramDeuxieme);

}
