
package fr.afcepf.atod26.lebaronjerome;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "serviceWebCalcul", targetNamespace = "http://lebaronjerome.atod26.afcepf.fr", wsdlLocation = "http://localhost:18080/WebService-ProjetWeb/operationService?wsdl")
public class ServiceWebCalcul
    extends Service
{

    private final static URL SERVICEWEBCALCUL_WSDL_LOCATION;
    private final static WebServiceException SERVICEWEBCALCUL_EXCEPTION;
    private final static QName SERVICEWEBCALCUL_QNAME = new QName("http://lebaronjerome.atod26.afcepf.fr", "serviceWebCalcul");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18080/WebService-ProjetWeb/operationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEWEBCALCUL_WSDL_LOCATION = url;
        SERVICEWEBCALCUL_EXCEPTION = e;
    }

    public ServiceWebCalcul() {
        super(__getWsdlLocation(), SERVICEWEBCALCUL_QNAME);
    }

    public ServiceWebCalcul(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEWEBCALCUL_QNAME, features);
    }

    public ServiceWebCalcul(URL wsdlLocation) {
        super(wsdlLocation, SERVICEWEBCALCUL_QNAME);
    }

    public ServiceWebCalcul(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEWEBCALCUL_QNAME, features);
    }

    public ServiceWebCalcul(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceWebCalcul(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceWeb
     */
    @WebEndpoint(name = "ServiceWebImplPort")
    public IServiceWeb getServiceWebImplPort() {
        return super.getPort(new QName("http://lebaronjerome.atod26.afcepf.fr", "ServiceWebImplPort"), IServiceWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceWeb
     */
    @WebEndpoint(name = "ServiceWebImplPort")
    public IServiceWeb getServiceWebImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://lebaronjerome.atod26.afcepf.fr", "ServiceWebImplPort"), IServiceWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEWEBCALCUL_EXCEPTION!= null) {
            throw SERVICEWEBCALCUL_EXCEPTION;
        }
        return SERVICEWEBCALCUL_WSDL_LOCATION;
    }

}
