
package fr.free.lebaronjerome;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMonServiceEJB", targetNamespace = "http://lebaronjerome.free.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMonServiceEJB {


    /**
     * 
     * @param paramDeuxieme
     * @param paramPremier
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "resultatDivision", targetNamespace = "")
    @RequestWrapper(localName = "diviser", targetNamespace = "http://lebaronjerome.free.fr", className = "fr.free.lebaronjerome.Diviser")
    @ResponseWrapper(localName = "diviserResponse", targetNamespace = "http://lebaronjerome.free.fr", className = "fr.free.lebaronjerome.DiviserResponse")
    public double diviser(
        @WebParam(name = "paramPremier", targetNamespace = "")
        int paramPremier,
        @WebParam(name = "paramDeuxieme", targetNamespace = "")
        int paramDeuxieme);

    /**
     * 
     * @param paramDeuxieme
     * @param paramPremier
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "resultatSoustraction", targetNamespace = "")
    @RequestWrapper(localName = "soustraire", targetNamespace = "http://lebaronjerome.free.fr", className = "fr.free.lebaronjerome.Soustraire")
    @ResponseWrapper(localName = "soustraireResponse", targetNamespace = "http://lebaronjerome.free.fr", className = "fr.free.lebaronjerome.SoustraireResponse")
    public int soustraire(
        @WebParam(name = "paramPremier", targetNamespace = "")
        int paramPremier,
        @WebParam(name = "paramDeuxieme", targetNamespace = "")
        int paramDeuxieme);

}
