
package fr.afcepf.atod26.webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MonServiceimpl", targetNamespace = "http://impl.webservice.atod26.afcepf.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MonServiceimpl {


    /**
     * 
     * @param deuxieme
     * @param premier
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addReturn", targetNamespace = "http://impl.webservice.atod26.afcepf.fr")
    @RequestWrapper(localName = "add", targetNamespace = "http://impl.webservice.atod26.afcepf.fr", className = "fr.afcepf.atod26.webservice.impl.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://impl.webservice.atod26.afcepf.fr", className = "fr.afcepf.atod26.webservice.impl.AddResponse")
    public int add(
        @WebParam(name = "premier", targetNamespace = "http://impl.webservice.atod26.afcepf.fr")
        int premier,
        @WebParam(name = "deuxieme", targetNamespace = "http://impl.webservice.atod26.afcepf.fr")
        int deuxieme);

    /**
     * 
     * @param deuxieme
     * @param premier
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "puissanceReturn", targetNamespace = "http://impl.webservice.atod26.afcepf.fr")
    @RequestWrapper(localName = "puissance", targetNamespace = "http://impl.webservice.atod26.afcepf.fr", className = "fr.afcepf.atod26.webservice.impl.Puissance")
    @ResponseWrapper(localName = "puissanceResponse", targetNamespace = "http://impl.webservice.atod26.afcepf.fr", className = "fr.afcepf.atod26.webservice.impl.PuissanceResponse")
    public double puissance(
        @WebParam(name = "premier", targetNamespace = "http://impl.webservice.atod26.afcepf.fr")
        int premier,
        @WebParam(name = "deuxieme", targetNamespace = "http://impl.webservice.atod26.afcepf.fr")
        int deuxieme);

}
