
package fr.afcepf.atod26.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MonServiceimplService", targetNamespace = "http://impl.webservice.atod26.afcepf.fr", wsdlLocation = "http://localhost:8080/WebService-Web/services/MonServiceimpl?wsdl")
public class MonServiceimplService
    extends Service
{

    private final static URL MONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MONSERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservice.atod26.afcepf.fr", "MonServiceimplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebService-Web/services/MonServiceimpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MonServiceimplService() {
        super(__getWsdlLocation(), MONSERVICEIMPLSERVICE_QNAME);
    }

    public MonServiceimplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MONSERVICEIMPLSERVICE_QNAME, features);
    }

    public MonServiceimplService(URL wsdlLocation) {
        super(wsdlLocation, MONSERVICEIMPLSERVICE_QNAME);
    }

    public MonServiceimplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MONSERVICEIMPLSERVICE_QNAME, features);
    }

    public MonServiceimplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonServiceimplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MonServiceimpl
     */
    @WebEndpoint(name = "MonServiceimpl")
    public MonServiceimpl getMonServiceimpl() {
        return super.getPort(new QName("http://impl.webservice.atod26.afcepf.fr", "MonServiceimpl"), MonServiceimpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MonServiceimpl
     */
    @WebEndpoint(name = "MonServiceimpl")
    public MonServiceimpl getMonServiceimpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.atod26.afcepf.fr", "MonServiceimpl"), MonServiceimpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return MONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
