
package fr.atod26.spring.lebaronjerome;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PersonneException", targetNamespace = "http://lebaronjerome.spring.atod26.fr")
public class PersonneException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PersonneException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PersonneException_Exception(String message, PersonneException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PersonneException_Exception(String message, PersonneException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.atod26.spring.lebaronjerome.PersonneException
     */
    public PersonneException getFaultInfo() {
        return faultInfo;
    }

}
