
package fr.atod26.spring.lebaronjerome;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PersonneExcecption", targetNamespace = "http://lebaronjerome.spring.atod26.fr")
public class PersonneExcecption_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PersonneExcecption faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PersonneExcecption_Exception(String message, PersonneExcecption faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PersonneExcecption_Exception(String message, PersonneExcecption faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.atod26.spring.lebaronjerome.PersonneExcecption
     */
    public PersonneExcecption getFaultInfo() {
        return faultInfo;
    }

}
