
package fr.atod26.spring.lebaronjerome;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "serviceSpringCXF", targetNamespace = "http://lebaronjerome.spring.atod26.fr", wsdlLocation = "http://localhost:8080/WebService-SpringCXF/services/springService?wsdl")
public class ServiceSpringCXF
    extends Service
{

    private final static URL SERVICESPRINGCXF_WSDL_LOCATION;
    private final static WebServiceException SERVICESPRINGCXF_EXCEPTION;
    private final static QName SERVICESPRINGCXF_QNAME = new QName("http://lebaronjerome.spring.atod26.fr", "serviceSpringCXF");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebService-SpringCXF/services/springService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICESPRINGCXF_WSDL_LOCATION = url;
        SERVICESPRINGCXF_EXCEPTION = e;
    }

    public ServiceSpringCXF() {
        super(__getWsdlLocation(), SERVICESPRINGCXF_QNAME);
    }

    public ServiceSpringCXF(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICESPRINGCXF_QNAME, features);
    }

    public ServiceSpringCXF(URL wsdlLocation) {
        super(wsdlLocation, SERVICESPRINGCXF_QNAME);
    }

    public ServiceSpringCXF(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICESPRINGCXF_QNAME, features);
    }

    public ServiceSpringCXF(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceSpringCXF(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceSpring
     */
    @WebEndpoint(name = "ServiceSpringImplPort")
    public IServiceSpring getServiceSpringImplPort() {
        return super.getPort(new QName("http://lebaronjerome.spring.atod26.fr", "ServiceSpringImplPort"), IServiceSpring.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceSpring
     */
    @WebEndpoint(name = "ServiceSpringImplPort")
    public IServiceSpring getServiceSpringImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://lebaronjerome.spring.atod26.fr", "ServiceSpringImplPort"), IServiceSpring.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICESPRINGCXF_EXCEPTION!= null) {
            throw SERVICESPRINGCXF_EXCEPTION;
        }
        return SERVICESPRINGCXF_WSDL_LOCATION;
    }

}
